export const totalManualSteps = 3;

export const seniorityOptions = ["Junior", "Mid", "Senior", "Staff and above"] as const;

export const locationOptions = [
  "Anywhere remote",
  "Bengaluru",
  "Hyderabad",
  "Pune",
  "Delhi",
  "Gurugram",
  "Noida",
  "Mumbai",
  "Chennai",
  "Kolkata",
  "Ahmedabad",
  "Kochi",
  "Thiruvananthapuram",
  "Coimbatore",
  "Mysuru",
  "Chandigarh/Mohali",
  "Jaipur",
  "Indore",
  "Bhubaneswar",
  "Singapore",
  "Kuala Lumpur",
  "Penang",
  "Johor Bahru",
  "Jakarta",
  "Bandung",
  "Ho Chi Minh City",
  "Hanoi",
  "Da Nang",
  "Bangkok",
  "Manila",
  "Cebu",
] as const;
